"""Pure OpenLineage construction and offline validation primitives."""

from streamt.integrations.openlineage.events import (
    EVENT_SCHEMA_URLS,
    FACET_SCHEMA_URLS,
    OPENLINEAGE_CORE_SCHEMA_ID,
    OPENLINEAGE_PRODUCER,
    OPENLINEAGE_RELEASE,
    DatasetIdentity,
    JobIdentity,
    OpenLineageConstructionError,
    RunIdentity,
    build_dataset_event,
    build_job_event,
    build_run_event,
    command_job_name,
    encode_job_segment,
    kafka_namespace_from_bootstrap,
    model_job_name,
    standard_facet,
    validate_kafka_namespace,
)
from streamt.integrations.openlineage.namespaces import (
    OpenLineageNamespaceError,
    OpenLineageNamespaces,
    resolve_openlineage_namespaces,
)
from streamt.integrations.openlineage.static import (
    OpenLineageExportWarning,
    OpenLineageStaticError,
    StaticNamespaceRequirements,
    StaticOpenLineageExport,
    build_static_export,
    serialize_static_jsonl,
    static_namespace_requirements,
)
from streamt.integrations.openlineage.transport import (
    FileTransportConfig,
    HttpTransportConfig,
    OpenLineageTransportConfig,
    OpenLineageTransportConfigurationError,
    load_openlineage_transport_config,
    parse_openlineage_transport_config,
)
from streamt.integrations.openlineage.validation import (
    OpenLineageResourceError,
    OpenLineageValidationError,
    event_kind,
    validate_event,
    validate_event_sequence,
    validate_standard_facet,
)

__all__ = [
    "EVENT_SCHEMA_URLS",
    "FACET_SCHEMA_URLS",
    "OPENLINEAGE_CORE_SCHEMA_ID",
    "OPENLINEAGE_PRODUCER",
    "OPENLINEAGE_RELEASE",
    "DatasetIdentity",
    "FileTransportConfig",
    "HttpTransportConfig",
    "JobIdentity",
    "OpenLineageConstructionError",
    "OpenLineageExportWarning",
    "OpenLineageNamespaceError",
    "OpenLineageNamespaces",
    "OpenLineageResourceError",
    "OpenLineageStaticError",
    "OpenLineageTransportConfig",
    "OpenLineageTransportConfigurationError",
    "OpenLineageValidationError",
    "RunIdentity",
    "StaticNamespaceRequirements",
    "StaticOpenLineageExport",
    "build_dataset_event",
    "build_job_event",
    "build_run_event",
    "build_static_export",
    "command_job_name",
    "encode_job_segment",
    "event_kind",
    "kafka_namespace_from_bootstrap",
    "load_openlineage_transport_config",
    "model_job_name",
    "parse_openlineage_transport_config",
    "resolve_openlineage_namespaces",
    "serialize_static_jsonl",
    "standard_facet",
    "static_namespace_requirements",
    "validate_event",
    "validate_event_sequence",
    "validate_kafka_namespace",
    "validate_standard_facet",
]
